In [52]:
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
import numpy as np

In [41]:
df = pd.read_csv("C:/Users/haywh/Desktop/unisalento/Phd courses/Data Analysis/PugliaAirQualityYear2023.csv")
df_copy = df.copy()
df.info()
df.head(20)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 258055 entries, 0 to 258054
Data columns (total 18 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   measurement_date           258055 non-null  object
 1    station_id                258055 non-null  int64
 2    name                      258055 non-null  object
 3    municipality              258055 non-null  object
 4    province                  258055 non-null  object
 5    longitude                 258055 non-null  float64
 6    latitude                  258055 non-null  float64
 7    area_type                 199290 non-null  object
 8    station_type              199290 non-null  object
 9    network                   258055 non-null  object
 10   network_interest          258055 non-null  object
 11   measured_pollutant        258055 non-null  object
 12   measured_pollutant_value  230228 non-null  float64
 13   limit                     244915 non-null  float64
 14   measurement_unit          258055 non-null  object
 15   exceedances               250755 non-null  float64
 16   quality_index             206551 non-null  float64
 17   quality_class             206551 non-null  object
dtypes: float64(6), int64(1), object(11)
memory usage: 35.4+ MB

,measurement_date,station_id,name,municipality,province,longitude,latitude,area_type,station_type,network,network_interest,measured_pollutant,measured_pollutant_value,limit,measurement_unit,exceedances,quality_index,quality_class
0,2023-01-01,64,Altamura - Via Santeramo,Altamura,Bari,16.561015,40.828848,Suburban,Soil,RRQA,PUBLIC,NO2,82.0,200.0,µg/m³,0.0,41.0,good
1,2023-01-01,64,Altamura - Via Santeramo,Altamura,Bari,16.561015,40.828848,Suburban,Soil,RRQA,PUBLIC,O3,62.0,180.0,µg/m³,0.0,34.0,good
2,2023-01-01,64,Altamura - Via Santeramo,Altamura,Bari,16.561015,40.828848,Suburban,Soil,RRQA,PUBLIC,PM10,55.0,50.0,µg/m³,7.0,109.0,poor
3,2023-01-01,64,Altamura - Via Santeramo,Altamura,Bari,16.561015,40.828848,Suburban,Soil,RRQA,PUBLIC,PM2.5,40.0,25.0,µg/m³,3.0,160.0,very bad
4,2023-01-01,17,Bari - Caldarola,Bari,Bari,16.888064,41.113542,Urban,Traffic,RRQA,PUBLIC,C6H6,1.0,5.0,µg/m³,0.0,20.0,excellent
5,2023-01-01,17,Bari - Caldarola,Bari,Bari,16.888064,41.113542,Urban,Traffic,RRQA,PUBLIC,CO,0.8,10.0,mg/m³,0.0,8.0,excellent
6,2023-01-01,17,Bari - Caldarola,Bari,Bari,16.888064,41.113542,Urban,Traffic,RRQA,PUBLIC,NO2,46.0,200.0,µg/m³,0.0,23.0,excellent
7,2023-01-01,17,Bari - Caldarola,Bari,Bari,16.888064,41.113542,Urban,Traffic,RRQA,PUBLIC,PM10,44.0,50.0,µg/m³,4.0,87.0,fair
8,2023-01-01,17,Bari - Caldarola,Bari,Bari,16.888064,41.113542,Urban,Traffic,RRQA,PUBLIC,PM2.5,36.0,25.0,µg/m³,12.0,144.0,poor
9,2023-01-01,81,Bari - Carbonara,Bari,Bari,16.866944,41.076666,Suburban,Soil,RRQA,PUBLIC,NO2,32.0,200.0,µg/m³,0.0,16.0,excellent
10,2023-01-01,81,Bari - Carbonara,Bari,Bari,16.866944,41.076666,Suburban,Soil,RRQA,PUBLIC,PM10,28.0,50.0,µg/m³,6.0,55.0,good
11,2023-01-01,81,Bari - Carbonara,Bari,Bari,16.866944,41.076666,Suburban,Soil,RRQA,PUBLIC,PM10,28.0,50.0,µg/m³,6.0,55.0,good
12,2023-01-01,81,Bari - Carbonara,Bari,Bari,16.866944,41.076666,Suburban,Soil,RRQA,PUBLIC,PM10,28.0,50.0,µg/m³,6.0,55.0,good
13,2023-01-01,81,Bari - Carbonara,Bari,Bari,16.866944,41.076666,Suburban,Soil,RRQA,PUBLIC,PM10,28.0,50.0,µg/m³,6.0,55.0,good
14,2023-01-01,81,Bari - Carbonara,Bari,Bari,16.866944,41.076666,Suburban,Soil,RRQA,PUBLIC,PM10,28.0,50.0,µg/m³,6.0,55.0,good
15,2023-01-01,54,Bari - Cavour,Bari,Bari,16.872552,41.122269,Urban,Traffic,RRQA,PUBLIC,C6H6,1.9,5.0,µg/m³,0.0,38.0,good
16,2023-01-01,54,Bari - Cavour,Bari,Bari,16.872552,41.122269,Urban,Traffic,RRQA,PUBLIC,CO,0.9,10.0,mg/m³,0.0,9.0,excellent
17,2023-01-01,54,Bari - Cavour,Bari,Bari,16.872552,41.122269,Urban,Traffic,RRQA,PUBLIC,CO,0.9,10.0,mg/m³,0.0,9.0,excellent
18,2023-01-01,54,Bari - Cavour,Bari,Bari,16.872552,41.122269,Urban,Traffic,RRQA,PUBLIC,CO,0.9,10.0,mg/m³,0.0,9.0,excellent
19,2023-01-01,54,Bari - Cavour,Bari,Bari,16.872552,41.122269,Urban,Traffic,RRQA,PUBLIC,CO,0.9,10.0,mg/m³,0.0,9.0,excellent

In [42]:
df.shape
df_copy.shape

(258055, 18)

In [43]:
columns = ['measurement_date', ' station_id', ' name', ' municipality',
       ' province', ' longitude', ' latitude', ' area_type', ' station_type',
       ' network', ' network_interest', ' measured_pollutant',
       ' measured_pollutant_value', ' limit', ' measurement_unit',
       ' exceedances', ' quality_index', ' quality_class']
df.columns = columns

num_df = [' measured_pollutant_value', ' limit',]
cat_data = df.drop(columns=num_df)
cat_df = cat_data.columns.tolist()
print(f"All columns: {columns}")
print(f"Category columns: {cat_df}")
print(f"Numerical column: {num_df}")

All columns: ['measurement_date', ' station_id', ' name', ' municipality', ' province', ' longitude', ' latitude', ' area_type', ' station_type', ' network', ' network_interest', ' measured_pollutant', ' measured_pollutant_value', ' limit', ' measurement_unit', ' exceedances', ' quality_index', ' quality_class']
Category columns: ['measurement_date', ' station_id', ' name', ' municipality', ' province', ' longitude', ' latitude', ' area_type', ' station_type', ' network', ' network_interest', ' measured_pollutant', ' measurement_unit', ' exceedances', ' quality_index', ' quality_class']
Numerical column: [' measured_pollutant_value', ' limit']

In [51]:
def data_cleaning(dataframe, numeric_columns_list, categorical_columns_list):
    dataframe_unclean = dataframe.copy() # Create a copy of the dataframe to avoid modifying the original
    columns_list = dataframe.columns.tolist() #convert the columns to a list
    dataframe = dataframe.drop_duplicates() #remove duplicates
    print(f"Removed {dataframe_unclean.shape[0] - dataframe.shape[0]} duplicates")
    
    #remove outliers
    for column in numeric_columns_list:
        Q1 = dataframe[column].quantile(0.25)  
        Q3 = dataframe[column].quantile(0.75)  
        IQR = Q3 - Q1  
        outliers = (dataframe[column] < (Q1 - 1.5*IQR)) | (dataframe[column] > (Q3 + 1.5*IQR)) 
        dataframe = dataframe[~outliers]
        print(f"Removed {outliers.sum()} outliers from {column}")
    return dataframe.describe()

df_no_outlier = data_cleaning(df, num_df, cat_df)
print(f"Shape before outlier removed: {df.shape}")
print(f"Shape after outlier removed: {df_no_outlier.shape}")

Removed 130998 duplicates
Removed 14281 outliers from  measured_pollutant_value
Removed 0 outliers from  limit
Shape before outlier removed: (258055, 18)
Shape after outlier removed: (8, 7)

In [49]:
def data_missing(dataframe, numeric_columns_list, categorical_columns_list):
    dataframe_unclean = dataframe.copy() # Create a copy of the dataframe to avoid modifying the original
    columns_list = dataframe.columns.tolist() #convert the columns to a list

    #remove missing values
    for column in columns_list:
        if column in numeric_columns_list:
            dataframe[column].fillna(dataframe[column].mean(), inplace=True)
        elif column in categorical_columns_list:
            #dataframe[column].fillna(dataframe[column].mode()[0], inplace=True) # This replaces NaN with the mode (most frequent value) of the column.

            """ 
            To replace NaN values in a categorical column according to the frequency distribution (instead of just the mode), 
            This ensures that missing values are filled in a way that preserves the original distribution of the data.
            This method replaces missing values in a categorical column while strictly preserving the original frequency 
            distribution across all categories (no randomness). It works for any number of categories
            """
            # Get frequency distribution of non-null values
            #column_distribution = dataframe[column].value_counts(normalize=True)  # Probabilities
            
            frequency_dist = dataframe[column].value_counts(normalize=True) # Probabilities
            missing_count = dataframe[column].isna().sum()
    
            # Step 2: Calculate exact imputation counts
            impute_counts = (frequency_dist * missing_count).round().astype(int)
            while impute_counts.sum() != missing_count:
                diff = missing_count - impute_counts.sum()
                impute_counts[impute_counts.idxmax()] += diff
    
            # Step 3: Replace missing values
            missing_indices = dataframe[dataframe[column].isna()].index.tolist()
            replacements = []
            for category, count in impute_counts.items():
                replacements.extend([category] * count)
            dataframe.loc[missing_indices, column] = replacements
            
            """ 
            To replace NaN values in a categorical column according to the frequency distribution (instead of just the mode), 
            use random sampling from the existing categories. 
            This ensures that missing values are filled in a way that preserves the original distribution of the data.
            """
            """
            dataframe[column] = dataframe[column].fillna(pd.Series(np.random.choice(
                column_distribution.index,
                size=len(dataframe),
                p=column_distribution.values)))
        """
        else:
            continue
    print("Data cleaning completed.")
        #print(f"Dataframe shape after cleaning: {dataframe.shape}\n Dataframe shape before cleaning: {dataframe_unclean.shape}")
        #print(f"Dataframe info after cleaning: {dataframe.info()}\n Dataframe info before cleaning: {dataframe_unclean.info()}")
        #print(f"Dataframe description after cleaning: {dataframe.describe()}\n Dataframe description before cleaning: {dataframe_unclean.describe()}")
    return dataframe.describe()

df_clean = data_missing(df_no_outlier, num_df, cat_df)

Data cleaning completed.

In [50]:
df.describe()

,station_id,longitude,latitude,measured_pollutant_value,limit,exceedances,quality_index
count,258055.000000,258055.000000,258055.000000,258055.000000,258055.000000,258055.000000,258055.000000
mean,63.202263,17.295700,40.726686,20.150248,60.208644,7.631916,21.759451
std,33.435854,0.738899,0.369520,69.193989,82.264101,30.991183,23.764499
min,8.000000,15.379722,40.123636,0.000000,5.000000,0.000000,0.000000
25%,33.000000,16.872552,40.488608,0.500000,10.000000,0.000000,4.000000
50%,64.000000,17.263602,40.624738,9.000000,25.000000,0.000000,11.000000
75%,96.000000,17.964477,41.076666,20.150248,50.000000,6.000000,34.000000
max,119.000000,18.294098,41.696944,2185.000000,350.000000,308.000000,484.000000

In [47]:
df.shape
df.isna().sum()

measurement_date             0
 station_id                  0
 name                        0
 municipality                0
 province                    0
 longitude                   0
 latitude                    0
 area_type                   0
 station_type                0
 network                     0
 network_interest            0
 measured_pollutant          0
 measured_pollutant_value    0
 limit                       0
 measurement_unit            0
 exceedances                 0
 quality_index               0
 quality_class               0
dtype: int64

In [48]:
df_clean.shape
df_clean.isna().sum()

 station_id                  0
 longitude                   0
 latitude                    0
 measured_pollutant_value    0
 limit                       0
 exceedances                 0
 quality_index               0
dtype: int64

{'Outstanding': [91, 92, 93, 94, 95, 96, 97, 98, 99, 100], 'Exceeds Expectations': [81, 82, 83, 84, 85, 86, 87, 88, 89, 90], 'Acceptable': [71, 72, 73, 74, 75, 76, 77, 78, 79, 80], 'Fail': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69]}
{'Harry': 'Exceeds Expectations', 'Ron': 'Acceptable', 'Hermione': 'Outstanding', 'Draco': 'Acceptable', 'Neville': 'Fail'}